version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout 
      - install_deps
      - run:
          name: run tests
          command: |
            npm run unit-tests
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - store_artifacts:
          path: ./

workflows:
  build-and-packge:
    jobs:
      - ci-build
      - pack:
          requires:
            - ci-build
          filters:
            branches:
              only:
                - master
            